
# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [soheil_p007, dnabook.official]
patreon: # Replace with a single Patreon soheilwikey12
open_collective: # Replace with a single Open Collective username
ko_fi: # Replace with a single Ko-fi @soheilwikey12
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay soheil_p007
issuehunt: # Replace with a single IssueHunt soheil.damanafshan
otechie: # Replace with a single Otechie @soheilwikey12
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://dnabookofficial.org/admin/', 'https://dnabookofficial.com']









repeat contribute for older my_project's 
soheil_p007@yahoo.com
soheil_p007@Outlook.com
soheil_p007@hotmail.com
